<?php
/**
 * Template for public Vivechan pages — mirrors the downloadable HTML document
 * inside the active theme's header/footer.
 *
 * @package Vivechan
 */

defined( 'ABSPATH' ) || exit;

use Vivechan\Services\HtmlRenderer;

get_header();

while ( have_posts() ) :
	the_post();
	?>
	<div class="vivechan-single">
		<style><?php echo HtmlRenderer::stylesheet(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></style>
		<div class="container">
			<?php echo get_the_content(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
			<div class="footer">Generated by Vivechan Transcriber · Geeta Pariwar Nepal</div>
		</div>
	</div>
	<?php
endwhile;

get_footer();
