<?php

namespace Vivechan\Services;

defined('ABSPATH') || exit;

use Vivechan\Helpers\Chapters;

/**
 * Renders a clean, printable Nepali-style HTML document from a completed
 * transcript, mirroring the curated Gita chapter format.
 *
 * The renderer is split so the same stylesheet + inner markup can be reused:
 *  - render()  → standalone HTML document (for the "Download HTML" action)
 *  - inner()   → the article body (title, shlokas, meta table) used as the
 *                WordPress post content
 *  - stylesheet() → the <style> block used on the public single-vivechan page
 */
final class HtmlRenderer {

	public static function render( $record, $meta = array() ) {
		$title = $record->name ?: ( $record->title ?: ( 'Transcript ' . $record->video_id ) );

		return '<!DOCTYPE html>
<html lang="ne">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>' . esc_html( $title ) . '</title>
<style>
' . self::stylesheet() . '
</style>
</head>
<body>
<div class="container">
	' . self::inner( $record, $meta ) . '
	<div class="footer">Generated by Vivechan Transcriber · Geeta Pariwar Nepal</div>
</div>
</body>
</html>';
	}

	/**
	 * Article body used both as post content and inside the full document.
	 */
	public static function inner( $record, $meta = array() ) {
		$content  = (string) $record->content;
		$chapter  = isset( $record->chapter ) ? (int) $record->chapter : 0;
		$level    = $chapter > 0 ? Chapters::level_for_chapter( $chapter ) : null;
		$chapter_label = $chapter > 0 ? Chapters::label( $chapter ) : '';

		if ( self::looks_like_html( $content ) ) {
			// Saved from the rich editor. The reviewer's own bold, headings and
			// lists are explicit, so the shloka heuristic is not applied — it
			// would fight the formatting they chose. Sanitised on the way in,
			// and again here, since this also renders the downloadable file.
			$body = wp_kses_post( $content );
		} else {
			// AI output and older rows are plain text.
			$paragraphs = self::paragraphs( $content );
			$body       = '';
			foreach ( $paragraphs as $p ) {
				$safe = self::inline_marks( esc_html( $p ) );

				$body .= self::is_shloka( $p )
					? '<p class="shloka">' . $safe . '</p>' . "\n"
					: '<p>' . $safe . '</p>' . "\n";
			}
		}

		if ( '' === trim( $body ) ) {
			$body = '<p><em>No transcript content yet.</em></p>' . "\n";
		}

		$meta_html = '';
		if ( ! empty( $meta ) ) {
			$rows = '';
			foreach ( $meta as $label => $value ) {
				if ( '' !== (string) $value ) {
					$rows .= '<tr><td>' . esc_html( $label ) . '</td><td>' . esc_html( $value ) . '</td></tr>' . "\n";
				}
			}
			if ( '' !== $rows ) {
				$meta_html = '<table class="meta-table"><tbody>' . $rows . '</tbody></table>' . "\n";
			}
		}

		$subtitle = '';
		if ( $chapter_label ) {
			$subtitle = '<p class="chapter-label">' . esc_html( $chapter_label ) . ( $level ? ' · ' . esc_html( $level ) : '' ) . '</p>';
		}

		$title = $record->name ?: ( $record->title ?: ( 'Transcript ' . $record->video_id ) );

		return '<h1>' . esc_html( $title ) . '</h1>' . "\n"
			. $subtitle . "\n"
			. $body
			. $meta_html;
	}

	public static function stylesheet() {
		return '
	* { box-sizing: border-box; margin: 0; padding: 0; }
	body { font-family: "Noto Sans Devanagari", "Kalimati", Arial, sans-serif; line-height: 1.9; font-size: 16px; background: #f4f6f9; color: #333; }
	.container { max-width: 860px; margin: 24px auto; background: #fff; padding: 44px 40px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); border-radius: 8px; }
	h1 { text-align: center; color: #b30000; font-size: 24px; border-bottom: 2px solid #eee; padding-bottom: 14px; margin-bottom: 8px; }
	.chapter-label { text-align: center; color: #777; font-size: 14px; margin-bottom: 26px; }
	p { margin-bottom: 1.05em; text-align: justify; }
	p.shloka { font-weight: bold; text-align: center; font-size: 1.12em; color: #b30000; }
	.meta-table { width: 100%; border-collapse: collapse; margin-top: 32px; font-size: 14px; }
	.meta-table th, .meta-table td { border: 1px solid #e0e0e0; padding: 10px 14px; text-align: left; }
	.meta-table th { background: #b30000; color: #fff; }
	.meta-table tr:nth-child(even) { background: #fafafa; }
	.footer { margin-top: 36px; padding-top: 16px; border-top: 2px solid #eee; text-align: center; color: #999; font-size: 13px; }
	@media print { body { background: #fff; } .container { box-shadow: none; margin: 0; padding: 20px; } }';
	}

	/**
	 * Turn the AI's **markers** into real emphasis.
	 *
	 * The system prompt asks for shlokas and Sanskrit terms in bold, and the
	 * model answers with markdown, but nothing ever interpreted it — the
	 * asterisks reached the published page verbatim.
	 *
	 * Runs AFTER esc_html, so the only tags that can appear are the ones added
	 * here; markup inside the transcript itself stays escaped.
	 */
	private static function inline_marks( $escaped ) {
		$out = preg_replace( '/\*\*(.+?)\*\*/u', '<strong>$1</strong>', $escaped );
		return null === $out ? $escaped : $out;
	}

	/**
	 * Does the stored content carry markup?
	 *
	 * Content saved from the rich editor is HTML; AI output and anything
	 * written before formatting was supported is plain text. Both have to keep
	 * rendering correctly, so they are told apart rather than migrated.
	 */
	private static function looks_like_html( $content ) {
		return (bool) preg_match( '#</?(p|br|strong|b|em|i|u|h[1-6]|ul|ol|li|blockquote)\b#i', (string) $content );
	}

	/**
	 * Split content into cleaned paragraphs.
	 */
	private static function paragraphs( $content ) {
		$content = trim( (string) $content );
		if ( '' === $content ) {
			return array();
		}
		$lines = preg_split( '/\R/', $content );
		$out   = array();
		$buffer = '';
		foreach ( $lines as $line ) {
			$line = trim( $line );
			if ( '' === $line ) {
				if ( '' !== $buffer ) {
					$out[] = $buffer;
					$buffer = '';
				}
				continue;
			}
			$buffer .= ( '' === $buffer ) ? $line : ' ' . $line;
		}
		if ( '' !== $buffer ) {
			$out[] = $buffer;
		}
		return $out;
	}

	/**
	 * Heuristic: treat short, punctuation-light Devanagari lines as shlokas.
	 */
	private static function is_shloka( $text ) {
		$t = trim( (string) $text );
		if ( '' === $t || mb_strlen( $t, 'UTF-8' ) > 200 ) {
			return false;
		}
		if ( ! preg_match( '/[\x{0900}-\x{097F}]+/u', $t ) ) {
			return false;
		}
		// Devanagari sentence punctuation ( । ॥ ॰ ) or question marks suggest prose.
		if ( preg_match( '/[।॥]/u', $t ) ) {
			return false;
		}
		// Latin script usually means prose or metadata.
		if ( preg_match( '/[A-Za-z]{2,}/', $t ) ) {
			return false;
		}
		$short       = mb_strlen( $t, 'UTF-8' ) <= 80;
		$space_count = substr_count( $t, ' ' );
		$token_avg   = $space_count > 0 ? mb_strlen( $t, 'UTF-8' ) / ( $space_count + 1 ) : mb_strlen( $t, 'UTF-8' );
		return $short || $token_avg >= 10;
	}
}
